Update to 1.19.2
zelytra/Daedalus pull request #189
Opened 2022-11-22 22:25 UTC by TimEpsilon

Updated Daedalus to 1.19.2

2022-11-24 08:08 UTC, zelytra requested changes
Beaucoup de modification a tester. Et modification nécessaire sur les liens du Motd qui on été retiré

2022-11-24 08:08 UTC, zelytra commented on src/main/java/fr/zelytra/daedalus/events/ServerPingListener.java
> +            e.setMotd("§6| §2Maze-Game §6ᒥ §8<< §6Daedalus §8>> §6ᒧ §§a             §6| §7Game Status §6: §fMaze Generation in progress...");
Suppressions des liens de l’application originel

2022-11-24 08:08 UTC, zelytra commented on src/main/java/fr/zelytra/daedalus/managers/guardian/Guardian.java
> +                if (this.spawnLoc.isWorldLoaded()) {
Vérifier que cette nouvelle méthode vérifier bien que le **chunk** est load et non pas le monde comme l'indique la méthode

2022-11-24 08:08 UTC, zelytra commented on src/main/java/fr/zelytra/daedalus/managers/guardian/Guardian.java
> +                spider.setHealth(28);
Vérifier que le max heal n'interfère pas avec le setHealth

2022-11-24 08:08 UTC, zelytra commented on src/main/java/fr/zelytra/daedalus/utils/Utils.java
> +        ep.b.a(status);
Vérification de l'affichage de l'animation tu Totem nécessaire avec la nouvelle méthode

2022-11-24 08:08 UTC, zelytra commented on pom.xml
> +
Utilité de cette nouvelle dépendance ?

2022-11-24 08:08 UTC, zelytra commented on src/main/java/fr/zelytra/daedalus/Daedalus.java
> +        File configLegacy = new File(Bukkit.getPluginManager().getPlugin("FastAsyncWorldEdit").getDataFolder().getPath() + File.separator + "worldedit-config.yml");
Vérifier la bonne modification du fichier de configuration. (A-t'il changé de nom ? Car il y a avais une spécificité sur le choix du fichier de config a modifier)

2022-11-24 08:10 UTC, zelytra commented
Modification du README.md a faire aussi afin de mettre a jour la documentation en lien avec les nouvelles versions

2022-11-24 08:16 UTC, zelytra commented
Modification nécessaire dans la version du plugin dans Utils.java -> setTabFx() -> V1.1

2022-11-24 21:26 UTC, TimEpsilon commented on src/main/java/fr/zelytra/daedalus/events/ServerPingListener.java
> +            e.setMotd("§6| §2Maze-Game §6ᒥ §8<< §6Daedalus §8>> §6ᒧ §§a             §6| §7Game Status §6: §fMaze Generation in progress...");
My bad, j'aurais du vérifier si le site était bien down, corrigé d'ici le prochain push

2022-11-24 22:12 UTC, TimEpsilon commented on src/main/java/fr/zelytra/daedalus/utils/Utils.java
> +        ep.b.a(status);
Testé et fonctionnel!

2022-12-04 12:07 UTC, zelytra reviewed
Il manque la mise a jour de la documentation (README.md)

2023-02-21 14:38 UTC, closed without merging